language: python

dist: xenial

cache: pip

notifications:
  email: true

matrix:
  include:
    # - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9

before_install:
- npm install npm@latest -g
- sudo apt-get update
- sudo apt-get install pandoc
- pip install pypandoc
- echo -e "machine github.ibm.com\n  login $GITHUB_OAUTH_TOKEN" > ~/.netrc
# - '[ "${TRAVIS_PULL_REQUEST}" == "false" ] && openssl aes-256-cbc -K $my_key -iv $my_iv -in myservice.env.enc -out myservice.env -d || true'

install:
- pip install tox-travis

script: tox


# To enable semantic-release, uncomment these sections.
# before_deploy:
# - pip install bump2version
# - nvm install 12
# - npm install @semantic-release/changelog
# - npm install @semantic-release/exec
# - npm install @semantic-release/git
# - npm install @semantic-release/github
# 
# deploy:
# - provider: script
#   script: npx semantic-release
#   skip_cleanup: true
#   on:
#     python: '3.6'
#     branch: main
# - provider: pypi
#   user: __token__
#   password: $PYPI_TOKEN
#   repository: https://upload.pypi.org/legacy
#   skip_cleanup: true
#   on:
#     python: '3.6'
#     tags: true
